### ISSUE TITLE
 Error: Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by adrianmak** [simonswiss/tailwind-starter#3]
$ gulp
[17:24:08] Using gulpfile F:\tailwind-starter-master\gulpfile.js
[17:24:08] Starting 'css'...
[17:24:08] 'css' errored after 6.16 ms
[17:24:08] Error: Cannot find module 'autoprefixer'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Gulp.gulp.task (F:\tailwind-starter-master\gulpfile.js:22:52)
    at module.exports (F:\tailwind-starter-master\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (F:\tailwind-starter-master\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (F:\tailwind-starter-master\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (F:\tailwind-starter-master\node_modules\orchestrator\index.js:134:8)
    at D:\nodejs_global_modules\node_modules\gulp\bin\gulp.js:129:20

**Comment by simonswiss** [comment]
I have added `autoprefixer` as a dev dependency in package.json in https://github.com/simonswiss/tailwind-starter/commit/65163499ea844dcaa7230ad0268e0e23930865ec
